services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: quattrex_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      NODE_ENV: production
      PORT: 3001
      SUPER_ADMIN_KEY: ${SUPER_ADMIN_KEY:-}
      ADMIN_IPS: ${ADMIN_IPS:-}
      NODE_OPTIONS: "--max-old-space-size=768"
    expose:
      - "3001"
    networks:
      - quattrex_network
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
    mem_limit: 1g
    mem_reservation: 512m
    cpus: '0.5'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://quattrex.pro/api
    container_name: quattrex_frontend
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=512"
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - quattrex_network
    restart: unless-stopped
    mem_limit: 768m
    mem_reservation: 384m
    cpus: '0.5'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: quattrex_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
      - ./backend/uploads:/app/uploads:ro
    depends_on:
      - frontend
      - backend
    networks:
      - quattrex_network
    restart: unless-stopped
    mem_limit: 256m
    mem_reservation: 128m

networks:
  quattrex_network:
    driver: bridge