-- AlterEnum
ALTER TYPE "BankType" ADD VALUE IF NOT EXISTS 'SOVCOMBANK';
ALTER TYPE "BankType" ADD VALUE IF NOT EXISTS 'ROSBANK';
ALTER TYPE "BankType" ADD VALUE IF NOT EXISTS 'UNICREDIT';
ALTER TYPE "BankType" ADD VALUE IF NOT EXISTS 'CITIBANK';
ALTER TYPE "BankType" ADD VALUE IF NOT EXISTS 'RUSSIANSTANDARD';
