-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deposit" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "disputeLimit" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "frozenPayoutBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxAmountPerRequisite" DOUBLE PRECISION NOT NULL DEFAULT 100000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxInsuranceDeposit" DOUBLE PRECISION NOT NULL DEFAULT 100000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxSimultaneousPayouts" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "minAmountPerRequisite" DOUBLE PRECISION NOT NULL DEFAULT 100;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "minPayoutAmount" DOUBLE PRECISION NOT NULL DEFAULT 100;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxPayoutAmount" DOUBLE PRECISION NOT NULL DEFAULT 1000000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payoutRateDelta" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payoutFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "minInsuranceDeposit" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "numericId" SERIAL;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payoutAcceptanceTime" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "payoutBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profitFromDeals" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profitFromPayouts" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "teamId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramBotToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramChatId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramDisputeChatId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "trustBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "User_numericId_key" ON "User"("numericId");