#!/bin/bash

# Demo script to simulate Chase app functionality

echo "================================================"
echo "       Chase Mobile App Demo"
echo "================================================"
echo ""
echo "📱 App launched successfully!"
echo ""
echo "🔍 QR Scanner Screen:"
echo "┌─────────────────────────────┐"
echo "│                             │"
echo "│        CHA\$ E              │"
echo "│                             │"
echo "│    ┌─────────────────┐      │"
echo "│    │                 │      │"
echo "│    │   QR SCANNER    │      │"
echo "│    │                 │      │"
echo "│    └─────────────────┘      │"
echo "│                             │"
echo "│    [Scan QR Code]           │"
echo "│                             │"
echo "│  Status: Connecting...      │"
echo "│                             │"
echo "│  [Enter Code Manually]      │"
echo "│                             │"
echo "└─────────────────────────────┘"
echo ""
echo "✅ Testing device connection..."
sleep 1

# Test device connection
DEVICE_TOKEN="test-device-token-123"
echo "📡 Connecting with device code: $DEVICE_TOKEN"
sleep 1

# Simulate successful connection
echo "✅ Device connected successfully!"
echo ""
echo "📊 Device Status:"
echo "  • Battery: 85%"
echo "  • Network: WiFi"
echo "  • Model: Test Device"
echo "  • Android: 14"
echo ""
echo "🔄 Monitoring notifications..."
echo "  • Listening for banking apps..."
echo "  • Sending device updates every 5 seconds..."
echo ""
echo "📨 Sample notification detected:"
echo "  • App: Сбербанк"
echo "  • Title: Перевод"
echo "  • Content: Поступление 5000 руб"
echo "  → Sent to server ✓"
echo ""
echo "🔄 Auto-update check:"
echo "  • Current version: 1.0.0"
echo "  • Latest version: 1.0.0"
echo "  • Up to date ✓"
echo ""
echo "================================================"
echo "Demo completed successfully!"