name: Install Docker on Server

on:
  workflow_dispatch:

jobs:
  install-docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Docker on server
        run: |
          echo "Installing Docker on server..."
          
          # Setup SSH
          mkdir -p ~/.ssh
          
          if [ -n "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
            chmod 600 ~/.ssh/deploy_key
            SSH_CMD="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no"
          else
            sudo apt-get update && sudo apt-get install -y sshpass
            SSH_CMD="sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -o StrictHostKeyChecking=no"
          fi
          
          # Connect and install Docker
          $SSH_CMD -p ${{ secrets.SERVER_PORT || '22' }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'INSTALL_SCRIPT'
          
          set -e
          
          echo "========================================"
          echo "Installing Docker..."
          echo "========================================"
          
          # Check if Docker is already installed
          if command -v docker &> /dev/null; then
              echo "Docker is already installed:"
              docker --version
              docker compose version || echo "Docker Compose not found"
              exit 0
          fi
          
          # Install prerequisites first
          echo "Installing prerequisites..."
          if command -v apt-get &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y curl wget ca-certificates gnupg lsb-release
          elif command -v yum &> /dev/null; then
              sudo yum install -y curl wget ca-certificates
          elif command -v dnf &> /dev/null; then
              sudo dnf install -y curl wget ca-certificates
          fi
          
          # Install Docker manually
          echo "Docker not found. Installing..."
          
          # Add Docker repository and install
          if [ -f /etc/debian_version ]; then
              # Debian/Ubuntu
              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              sudo chmod a+r /etc/apt/keyrings/docker.gpg
              
              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs 2>/dev/null || echo focal) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io || \
                sudo apt-get install -y docker.io
          elif [ -f /etc/redhat-release ]; then
              # RedHat/CentOS
              sudo yum install -y yum-utils
              sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              sudo yum install -y docker-ce docker-ce-cli containerd.io || \
                sudo yum install -y docker
          else
              echo "ERROR: Unsupported system for Docker installation"
              exit 1
          fi
          
          # Enable Docker service
          sudo systemctl enable docker
          sudo systemctl start docker
          
          # Add user to docker group
          sudo usermod -aG docker $USER
          
          # Install docker-compose plugin
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin || true
          
          # Verify installation
          echo ""
          echo "Installation complete. Verifying..."
          sudo docker --version
          sudo docker compose version
          
          echo ""
          echo "========================================"
          echo "Docker installed successfully!"
          echo "========================================"
          
          INSTALL_SCRIPT
          
          echo "Docker installation completed!"